"""
db_loader.py
============
Loads all data this project needs directly from the PostgreSQL database
generated by data_generator.py.

Replaces data_generator.py's three public functions with live DB queries:
  generate_dataset()   ->  DBLoader.load_metrics()
  get_topology()       ->  DBLoader.get_topology()
  get_target_events()  ->  DBLoader.get_target_events()

Output shape is IDENTICAL to data_generator.py so every other module
(topology_loader, feature_engine, pattern_discovery, inference_engine,
pattern_storage, rediscovery_engine) works completely unchanged.

  load_metrics()      -> DataFrame(timestamp, device, metric, value)
  get_topology()      -> {"nodes":[{"id","role"}], "edges":[[a,b]..]}
  get_target_events() -> [{"device","metric","event","severity"}]

Usage
-----
    from db_loader import DBLoader
    loader      = DBLoader("postgresql://postgres:password@localhost:5432/pattern_mining")
    df          = loader.load_metrics(days=30)
    topology    = loader.get_topology()
    target_evts = loader.get_target_events()
    loader.close()

CLI self-test
-------------
    python db_loader.py --db postgresql://... --days 7
"""

from __future__ import annotations

import argparse
from datetime import datetime, timedelta, timezone
from typing import Callable, Optional

import pandas as pd
import psycopg2
import psycopg2.extras


# ── Column lists matching the DB schema ──────────────────────────────────────

IFACE_METRIC_COLS = [
    "rx_bps", "tx_bps", "rx_util_pct", "tx_util_pct",
    "rx_errors", "tx_errors", "rx_drops", "tx_drops",
    "crc_errors", "input_discards", "output_discards",
    "flap_count", "latency_ms", "jitter_ms",
]

DEVICE_METRIC_COLS = [
    "cpu_pct", "mem_util_pct", "temp_c",
    "fan_speed_rpm", "power_supply_status",
]

# event_type -> (metric_column, source)
EVENT_TO_METRIC: dict[str, tuple[str, str]] = {
    "HIGH_LATENCY":        ("latency_ms",          "interface"),
    "CRITICAL_LATENCY":    ("latency_ms",          "interface"),
    "LINK_FLAP":           ("flap_count",          "interface"),
    "HIGH_UTILIZATION":    ("rx_util_pct",         "interface"),
    "CRITICAL_UTIL":       ("rx_util_pct",         "interface"),
    "RX_ERROR_SPIKE":      ("rx_errors",           "interface"),
    "TX_ERROR_SPIKE":      ("tx_errors",           "interface"),
    "CRC_ERRORS":          ("crc_errors",          "interface"),
    "INPUT_DISCARD_SPIKE": ("input_discards",      "interface"),
    "HIGH_CPU":            ("cpu_pct",             "device"),
    "CRITICAL_CPU":        ("cpu_pct",             "device"),
    "MEMORY_EXHAUSTION":   ("mem_util_pct",        "device"),
    "HIGH_TEMPERATURE":    ("temp_c",              "device"),
    "CRITICAL_TEMPERATURE":("temp_c",              "device"),
    "FAN_DEGRADED":        ("fan_speed_rpm",       "device"),
    "POWER_SUPPLY_FAIL":   ("power_supply_status", "device"),
    "DEVICE_REBOOT":       ("cpu_pct",             "device"),
}

EVENT_SEVERITY: dict[str, str] = {
    "HIGH_LATENCY":        "warning",
    "CRITICAL_LATENCY":    "critical",
    "LINK_FLAP":           "critical",
    "HIGH_UTILIZATION":    "warning",
    "CRITICAL_UTIL":       "critical",
    "RX_ERROR_SPIKE":      "warning",
    "TX_ERROR_SPIKE":      "warning",
    "CRC_ERRORS":          "warning",
    "INPUT_DISCARD_SPIKE": "warning",
    "HIGH_CPU":            "warning",
    "CRITICAL_CPU":        "critical",
    "MEMORY_EXHAUSTION":   "critical",
    "HIGH_TEMPERATURE":    "warning",
    "CRITICAL_TEMPERATURE":"critical",
    "FAN_DEGRADED":        "warning",
    "POWER_SUPPLY_FAIL":   "critical",
    "DEVICE_REBOOT":       "critical",
}


# =============================================================================
class DBLoader:
# =============================================================================

    def __init__(self, db_url: str):
        self.db_url = db_url
        self._conn: Optional[psycopg2.extensions.connection] = None

    # ── Connection ────────────────────────────────────────────────────────

    def _connect(self) -> psycopg2.extensions.connection:
        if self._conn is None or self._conn.closed:
            self._conn = psycopg2.connect(self.db_url)
            self._conn.autocommit = True
        return self._conn

    def close(self) -> None:
        if self._conn and not self._conn.closed:
            self._conn.close()

    def _query(self, sql: str, params: tuple = ()) -> list[dict]:
        conn = self._connect()
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, params)
            return [dict(r) for r in cur.fetchall()]

    # ── Clause builders ───────────────────────────────────────────────────

    def _time_filter(
        self, days: Optional[int], col: str = "ts"
    ) -> tuple[str, list]:
        if days:
            cutoff = datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(days=days)
            return f"AND {col} >= %s", [cutoff]
        return "", []

    def _iface_scope(
        self, device_type: Optional[str], device_id: Optional[str]
    ) -> tuple[str, list]:
        if device_id:
            return "AND im.entity_id LIKE %s", [f"{device_id}:%"]
        if device_type:
            return "AND im.device_type = %s", [device_type]
        return "", []

    def _dev_scope(
        self, device_type: Optional[str], device_id: Optional[str]
    ) -> tuple[str, list]:
        if device_id:
            return "AND dm.device_id = %s", [device_id]
        if device_type:
            return "AND dm.device_type = %s", [device_type]
        return "", []

    # =========================================================================
    # 1.  load_metrics()   replaces  generate_dataset()
    # =========================================================================

    def load_metrics(
        self,
        days:         Optional[int] = None,
        device_type:  Optional[str] = None,
        device_id:    Optional[str] = None,
        sample_every: int = 1,
    ) -> pd.DataFrame:
        """
        Return long-format DataFrame  (timestamp, device, metric, value).

        Combines interface metrics + device-level resource metrics.
        'device' = device_id portion of entity_id
            e.g.  "router-01:Gi0/0/0"  ->  "router-01"

        Parameters
        ----------
        days         : restrict to last N days  (None = all data)
        device_type  : e.g. "router"
        device_id    : e.g. "router-01"
        sample_every : keep every Nth row per (device,metric) -- memory control
                       Recommended: 2 or 3 for 90-day datasets
        """
        tc,  tp  = self._time_filter(days)
        isc, isp = self._iface_scope(device_type, device_id)
        dsc, dsp = self._dev_scope(device_type, device_id)

        # ── interface_metrics ─────────────────────────────────────────────
        i_cols = ", ".join(f"im.{c}" for c in IFACE_METRIC_COLS)
        iface_rows = self._query(f"""
            SELECT im.ts AS timestamp, im.entity_id, {i_cols}
            FROM   interface_metrics im
            WHERE  1=1 {isc} {tc}
            ORDER  BY im.entity_id, im.ts
        """, tuple(isp + tp))

        # ── device_metrics ────────────────────────────────────────────────
        d_cols = ", ".join(f"dm.{c}" for c in DEVICE_METRIC_COLS)
        dev_rows = self._query(f"""
            SELECT dm.ts AS timestamp, dm.device_id AS entity_id, {d_cols}
            FROM   device_metrics dm
            WHERE  1=1 {dsc} {tc}
            ORDER  BY dm.device_id, dm.ts
        """, tuple(dsp + tp))

        if not iface_rows and not dev_rows:
            raise ValueError(
                "No metric data found. "
                "Check --days / --device-type / --device-id, "
                "or verify the database has been seeded."
            )

        # ── pivot wide -> long ────────────────────────────────────────────
        iface_long = _wide_to_long(
            iface_rows, IFACE_METRIC_COLS,
            device_fn=lambda eid: eid.split(":")[0],
        )
        dev_long = _wide_to_long(
            dev_rows, DEVICE_METRIC_COLS,
            device_fn=lambda eid: eid,
        )

        # ── concat — skip empty frames so pandas never merges two empty shells ──
        frames = [f for f in [iface_long, dev_long] if not f.empty]
        if not frames:
            raise ValueError(
                "No metric data found for the requested scope. "
                "Check DEVICE_TYPE / DEVICE_ID / DAYS settings, "
                "or verify the database has been seeded."
            )
        df = pd.concat(frames, ignore_index=True)

        # Defensive column check — report clearly what went wrong
        _REQUIRED = ["timestamp", "device", "metric", "value"]
        missing = [c for c in _REQUIRED if c not in df.columns]
        if missing:
            raise ValueError(
                f"Columns {missing} missing after pivot. "
                f"Actual columns: {list(df.columns)}. "
                f"iface_rows={len(iface_rows)}, dev_rows={len(dev_rows)}, "
                f"iface_long.shape={iface_long.shape}, dev_long.shape={dev_long.shape}"
            )

        df["timestamp"] = pd.to_datetime(df["timestamp"]).dt.tz_localize(None)
        df = df.dropna(subset=["value"])
        df = df.sort_values(["device", "metric", "timestamp"]).reset_index(drop=True)

        # ── Sub-sampling: use plain iloc slice per group, never groupby().apply()
        # (groupby().apply() can silently drop columns in some pandas versions)
        if sample_every > 1:
            parts = []
            for _, grp in df.groupby(["device", "metric"], sort=False):
                parts.append(grp.iloc[::sample_every])
            df = pd.concat(parts, ignore_index=True).sort_values(
                ["device", "metric", "timestamp"]
            ).reset_index(drop=True)

        t0, t1 = df["timestamp"].min(), df["timestamp"].max()
        print(f"  [DBLoader] metrics : {len(df):,} rows | "
              f"{df['device'].nunique()} devices | "
              f"{df['metric'].nunique()} metrics | "
              f"{t0} -> {t1}")
        return df

    # =========================================================================
    # 2.  get_topology()   replaces  get_topology() in data_generator.py
    # =========================================================================

    def get_topology(
        self,
        device_type: Optional[str] = None,
        device_id:   Optional[str] = None,
    ) -> dict:
        """
        Build topology dict from devices + interfaces tables.

        Returns same shape as data_generator.get_topology():
            {
              "nodes": [{"id": "router-01", "role": "router"}, ...],
              "edges": [["router-01", "switch-01"], ...]
            }

        Edge inference:
          1. Interface description contains peer device-id name -> direct edge
          2. Fallback: linear chain by device_type order
        """
        where, params = "", []
        if device_id:
            where, params = "WHERE id = %s", [device_id]
        elif device_type:
            where, params = "WHERE device_type = %s", [device_type]

        dev_rows = self._query(
            f"SELECT id, device_type FROM devices {where} ORDER BY device_type, id",
            tuple(params),
        )
        if not dev_rows:
            raise ValueError("No devices found in the database.")

        nodes      = [{"id": r["id"], "role": r["device_type"]} for r in dev_rows]
        device_ids = {r["id"] for r in dev_rows}

        # ── Infer edges from interface descriptions ───────────────────────
        ifaces = self._query("""
            SELECT device_id, interface_name, description
            FROM   interfaces WHERE is_active = TRUE
        """)

        uplink_kw = {
            "uplink", "trunk", "peer", "core", "transit",
            "port-channel", "bundle", "ae", "lacp",
        }
        edges: list[list[str]] = []
        seen:  set[frozenset]  = set()

        for row in ifaces:
            dev_a = row["device_id"]
            desc  = (row["description"]    or "").lower()
            iname = (row["interface_name"] or "").lower()

            if not any(kw in desc or kw in iname for kw in uplink_kw):
                continue

            for did in device_ids:
                if did != dev_a and did.lower() in desc:
                    key = frozenset({dev_a, did})
                    if key not in seen:
                        seen.add(key)
                        edges.append([dev_a, did])
                    break

        # ── Fallback: linear chain by type order ──────────────────────────
        if not edges:
            type_order = ["router", "switch", "firewall", "load_balancer"]
            grouped: dict[str, list[str]] = {}
            for r in dev_rows:
                grouped.setdefault(r["device_type"], []).append(r["id"])

            chain: list[str] = []
            for dt in type_order:
                chain.extend(grouped.get(dt, []))
            for dt, devs in grouped.items():
                if dt not in type_order:
                    chain.extend(devs)

            for i in range(len(chain) - 1):
                key = frozenset({chain[i], chain[i + 1]})
                if key not in seen:
                    seen.add(key)
                    edges.append([chain[i], chain[i + 1]])

        print(f"  [DBLoader] topology: {len(nodes)} nodes, {len(edges)} edges")
        return {"nodes": nodes, "edges": edges}

    # =========================================================================
    # 3.  get_target_events()  replaces  get_target_events() in data_generator
    # =========================================================================

    def get_target_events(
        self,
        device_type: Optional[str] = None,
        device_id:   Optional[str] = None,
        days:        Optional[int] = None,
        top_n:       int = 5,
    ) -> list[dict]:
        """
        Derive target events from what actually exists in the events table.

        Returns same shape as data_generator.get_target_events():
            [{"device": "router-01", "metric": "latency_ms",
              "event": "HIGH_LATENCY", "severity": "critical"}, ...]

        Picks the top_n most frequent event_types, maps each to its
        corresponding metric column, and resolves a representative device.
        """
        tc, tp = self._time_filter(days)

        dev_filter, dev_params = "", []
        if device_id:
            dev_filter, dev_params = "AND device_id = %s", [device_id]
        elif device_type:
            dev_filter, dev_params = "AND device_type = %s", [device_type]

        rows = self._query(f"""
            SELECT
                event_type,
                device_type,
                COUNT(*) AS cnt,
                MODE() WITHIN GROUP (ORDER BY device_id) AS rep_device
            FROM events
            WHERE 1=1 {dev_filter} {tc}
            GROUP BY event_type, device_type
            ORDER BY cnt DESC
            LIMIT %s
        """, tuple(dev_params + tp + [top_n * 4]))

        targets: list[dict] = []
        seen:    set[str]   = set()

        for row in rows:
            etype = row["event_type"]
            if etype in seen or etype not in EVENT_TO_METRIC:
                continue
            metric_col, _ = EVENT_TO_METRIC[etype]
            seen.add(etype)
            targets.append({
                "device":   row["rep_device"],
                "metric":   metric_col,
                "event":    etype,
                "severity": EVENT_SEVERITY.get(etype, "warning"),
            })
            if len(targets) >= top_n:
                break

        # Fallback if events table is empty
        if not targets:
            targets = [
                {"device": None, "metric": "latency_ms",  "event": "HIGH_LATENCY",    "severity": "critical"},
                {"device": None, "metric": "rx_util_pct", "event": "HIGH_UTILIZATION", "severity": "warning"},
                {"device": None, "metric": "cpu_pct",     "event": "HIGH_CPU",         "severity": "warning"},
            ]

        # Resolve None device
        for t in targets:
            if t["device"] is None:
                t["device"] = self._first_device_with_metric(t["metric"], device_type)

        print(f"  [DBLoader] target events: {[t['event'] for t in targets]}")
        return targets

    # =========================================================================
    # 4.  load_recent_window()  -- used by inference engine
    # =========================================================================

    def load_recent_window(
        self,
        window_minutes: int = 75,
        device_type:    Optional[str] = None,
        device_id:      Optional[str] = None,
    ) -> pd.DataFrame:
        """
        Load only the most recent window_minutes of data.
        Used by the inference engine on each new poll cycle.
        """
        days_needed = max(1, window_minutes // (60 * 24) + 1)
        df = self.load_metrics(days=days_needed,
                               device_type=device_type,
                               device_id=device_id)
        cutoff = df["timestamp"].max() - pd.Timedelta(minutes=window_minutes)
        return df[df["timestamp"] >= cutoff].reset_index(drop=True)

    # ── Internal ──────────────────────────────────────────────────────────

    def _first_device_with_metric(
        self, metric: str, device_type: Optional[str] = None
    ) -> str:
        dt_p = [device_type] if device_type else []
        if metric in IFACE_METRIC_COLS:
            dft = "AND im.device_type = %s" if device_type else ""
            sql = f"""
                SELECT SPLIT_PART(im.entity_id, ':', 1) AS device_id
                FROM   interface_metrics im
                WHERE  im.{metric} IS NOT NULL {dft} LIMIT 1
            """
        else:
            dft = "AND dm.device_type = %s" if device_type else ""
            sql = f"""
                SELECT dm.device_id FROM device_metrics dm
                WHERE  dm.{metric} IS NOT NULL {dft} LIMIT 1
            """
        rows = self._query(sql, tuple(dt_p))
        return rows[0]["device_id"] if rows else "router-01"


# =============================================================================
# Internal pivot helper
# =============================================================================

def _wide_to_long(
    rows:        list[dict],
    metric_cols: list[str],
    device_fn:   Callable[[str], str],
) -> pd.DataFrame:
    """Convert wide-format row dicts to long-format (timestamp, device, metric, value)."""
    EMPTY = pd.DataFrame(columns=["timestamp", "device", "metric", "value"])

    if not rows:
        return EMPTY

    df_wide = pd.DataFrame(rows)

    # entity_id must be present
    if "entity_id" not in df_wide.columns:
        return EMPTY

    df_wide["device"] = df_wide["entity_id"].apply(device_fn)

    # Keep only metric columns that actually exist in the result
    present_cols = [c for c in metric_cols if c in df_wide.columns]
    if not present_cols:
        return EMPTY

    # Use pd.melt — handles NULLs cleanly and never drops columns
    df_long = df_wide[["timestamp", "device"] + present_cols].melt(
        id_vars    = ["timestamp", "device"],
        value_vars = present_cols,
        var_name   = "metric",
        value_name = "value",
    )
    df_long = df_long.dropna(subset=["value"])

    if df_long.empty:
        return EMPTY

    return df_long[["timestamp", "device", "metric", "value"]].reset_index(drop=True)


# =============================================================================
# CLI self-test
# =============================================================================

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="DBLoader self-test")
    ap.add_argument("--db",          required=True)
    ap.add_argument("--days",        type=int, default=7)
    ap.add_argument("--device-type", default=None)
    ap.add_argument("--device-id",   default=None)
    ap.add_argument("--top-n",       type=int, default=5)
    args = ap.parse_args()

    bar = "=" * 60
    print(f"\n{bar}\n  DBLoader self-test\n  DB  : {args.db}\n{bar}")

    loader = DBLoader(args.db)

    print("\n[1/3] Metrics ...")
    df = loader.load_metrics(
        days=args.days,
        device_type=args.device_type,
        device_id=args.device_id,
    )
    print(f"      Devices : {sorted(df['device'].unique())}")
    print(f"      Metrics : {sorted(df['metric'].unique())}")
    print(df.head(8).to_string(index=False))

    print("\n[2/3] Topology ...")
    topo = loader.get_topology(device_type=args.device_type,
                               device_id=args.device_id)
    for n in topo["nodes"][:6]:
        print(f"      {n['id']:25s}  role={n['role']}")
    for e in topo["edges"][:6]:
        print(f"      {e[0]} -- {e[1]}")

    print("\n[3/3] Target events ...")
    for t in loader.get_target_events(
        device_type=args.device_type,
        device_id=args.device_id,
        days=args.days,
        top_n=args.top_n,
    ):
        print(f"      {t['event']:28s}  device={t['device']:20s}  "
              f"metric={t['metric']:18s}  sev={t['severity']}")

    print(f"\n{bar}\n  All OK\n{bar}\n")
    loader.close()